### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by dcov** [impulse/Lenovo-Flex-15-Hackintosh#6]
Wasn't sure where else to ask, so my apologies if this is the wrong place, and I'll close it right away.

Basically I'm having trouble installing Catalina 10.15.3 onto my Flex 15. I'm new to the whole process so I'm not sure where I'm going wrong, and since it appears that you have the same laptop as me, I though I'd ask you.

First problem I had was that my usb wasn't being detected as a boot option when I configured it as a UEFI boot. So then I switched it to be a Legacy boot, and now it just hangs on the apple logo with an empty progress bar.

I copied the kexts files to CLOVER/kexts/Other.
I copied the misc folder to CLOVER/misc
I copied the config.plist file to CLOVER/config.plist
I copied the ACPI/patched files to CLOVER/ACPI/patched

Is there anything I've missed? Did you face the same issue with booting it in UEFI mode?

Thanks.

**Comment by impulse** [comment]
Probably you run into power management issues on Catalina while booting from the USB. I haven't updated this repo in quite some time but I have a working EFI folder which I may be able to upload this weekend. Legacy boot is not required for this laptop and I would also no recommend doing so. Can you provide the error using `-v debug=0x100` bootargs?

**Comment by dcov** [comment]
Yeah it turns out I was just formatting the usb wrong. I got it to boot using the tonymacx86 install guide, but then it got stuck on the Apple logo with a full progress bar.

Also, I haven't been able to test the files in this repo because whenever I use them Clover doesn't show OSx as an Install option, it only shows a Grub option for my current Linux install. But as I mentioned before, if I use the default tonymacx86 UniBeast configuration, without adding/changing any files, it works up until it hangs on apfs_module_start .... 1386, or something along those lines.

Thanks for getting back to me though, appreciate it. Also, just to ask, what year is your Flex 15? Just to make sure we have roughly the same model. Mine is ~2014.

**Comment by impulse** [comment]
> until it hangs on apfs_module_start .... 1386, or something along those lines.

Yeah that's the usb power issue, for Catalina to work a proper USB mapping is required (which is not in the repo atm). I didn't do a fresh install on this laptop since I upgraded from Mojave. Already got this resolved locally though.

3 Options for you:
1) Make the Catalina install on another computer then manually add an UEFI boot entry -> USB map
2) Make a Mojave installer then install Mojave on your Laptop -> USB map -> Upgrade to Catalina
3) Wait for me to upload my USB map and install Catalina directly

> Mine is ~2014.
Yeah mine is around the same age. Just check the number on the back sticker

**Comment by dcov** [comment]
Well I got Catalina working. I found a different patch for the ACPI issue I was facing earlier which fixed the earlier issue. Also, I still have to boot through my usb because if I try to boot using my hdd it hangs on 'IOConsoleUsers: gIOScreenLockState..'. It appears to be an issue with my Clover install so I'll have to look into it. Also my touchpad gestures don't work either.

With that said, I really appreciate this repo and your help. The Voodoo... and Realtek... kext files came in handy for my keyboard and ethernet functionality. Also, I'm still looking forward to seeing your config whenever you have time to upload. Thanks again.

**Comment by impulse** [comment]
@dcov just letting you know that I updated the repo to my current config. Since 10.15.1 or so a proper usb port limit configuration is needed to have USB3 and Bluetooth working properly. In case the provided kext doesn't work for you, you will need to do this manually. This will also solve the issue you described with the laptop not being able to boot from USB.
